-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity addsub is
port (
    a_V : IN STD_LOGIC_VECTOR (78 downto 0);
    b_V : IN STD_LOGIC_VECTOR (76 downto 0);
    add : IN STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (79 downto 0) );
end;


architecture behav of addsub is 
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv78_0 : STD_LOGIC_VECTOR (77 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal b_V_cast1_fu_38_p1 : STD_LOGIC_VECTOR (77 downto 0);
    signal p_Val2_s_33_fu_48_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_fu_42_p2 : STD_LOGIC_VECTOR (77 downto 0);
    signal p_Val2_s_33_fu_48_p3 : STD_LOGIC_VECTOR (77 downto 0);
    signal tmp_s_fu_56_p1 : STD_LOGIC_VECTOR (79 downto 0);
    signal tmp_34_fu_60_p1 : STD_LOGIC_VECTOR (79 downto 0);


begin



    ap_return <= std_logic_vector(signed(tmp_s_fu_56_p1) + signed(tmp_34_fu_60_p1));
        b_V_cast1_fu_38_p1 <= std_logic_vector(resize(signed(b_V),78));

    p_Val2_s_33_fu_48_p0 <= (0=>add, others=>'-');
    p_Val2_s_33_fu_48_p3 <= 
        b_V_cast1_fu_38_p1 when (p_Val2_s_33_fu_48_p0(0) = '1') else 
        p_Val2_s_fu_42_p2;
    p_Val2_s_fu_42_p2 <= std_logic_vector(unsigned(ap_const_lv78_0) - unsigned(b_V_cast1_fu_38_p1));
        tmp_34_fu_60_p1 <= std_logic_vector(resize(signed(p_Val2_s_33_fu_48_p3),80));

        tmp_s_fu_56_p1 <= std_logic_vector(resize(signed(a_V),80));

end behav;
