# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/v7_bd/v7_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd || ORIG_REF_NAME==v7_bd}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_cap_ram_1_0/v7_bd_axi_bram_ctrl_cap_ram_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_cap_ram_1_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_cap_ram_1_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_reg_file_0/v7_bd_axi_bram_ctrl_reg_file_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_reg_file_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_reg_file_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_chip2chip_0_0 || ORIG_REF_NAME==v7_bd_axi_chip2chip_0_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_interconnect_0_0/v7_bd_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_interconnect_0_0 || ORIG_REF_NAME==v7_bd_axi_interconnect_0_0}]

# IP: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_clk_wiz_0_0 || ORIG_REF_NAME==v7_bd_clk_wiz_0_0}]

# IP: bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==v7_bd_proc_sys_reset_0_0}]

# IP: bd/v7_bd/ip/v7_bd_xadc_wiz_0_0/v7_bd_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_xadc_wiz_0_0 || ORIG_REF_NAME==v7_bd_xadc_wiz_0_0}]

# IP: bd/v7_bd/ip/v7_bd_xbar_0/v7_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_xbar_0 || ORIG_REF_NAME==v7_bd_xbar_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_input_ram_0_0/v7_bd_axi_bram_ctrl_input_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_input_ram_0_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_input_ram_0_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_input_ram_4_0/v7_bd_axi_bram_ctrl_input_ram_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_input_ram_4_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_input_ram_4_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_output_ram_0_0/v7_bd_axi_bram_ctrl_output_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_output_ram_0_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_output_ram_0_0}]

# IP: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_input_ram_1_0/v7_bd_axi_bram_ctrl_input_ram_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_axi_bram_ctrl_input_ram_1_0 || ORIG_REF_NAME==v7_bd_axi_bram_ctrl_input_ram_1_0}]

# IP: bd/v7_bd/ip/v7_bd_s00_regslice_0/v7_bd_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_s00_regslice_0 || ORIG_REF_NAME==v7_bd_s00_regslice_0}]

# IP: bd/v7_bd/ip/v7_bd_s00_data_fifo_0/v7_bd_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_s00_data_fifo_0 || ORIG_REF_NAME==v7_bd_s00_data_fifo_0}]

# IP: bd/v7_bd/ip/v7_bd_m02_regslice_0/v7_bd_m02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v7_bd_m02_regslice_0 || ORIG_REF_NAME==v7_bd_m02_regslice_0}]

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_cap_ram_1_0/v7_bd_axi_bram_ctrl_cap_ram_1_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_reg_file_0/v7_bd_axi_bram_ctrl_reg_file_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_axi_chip2chip_0_0 || ORIG_REF_NAME==v7_bd_axi_chip2chip_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_axi_chip2chip_0_0 || ORIG_REF_NAME==v7_bd_axi_chip2chip_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_axi_chip2chip_0_0/v7_bd_axi_chip2chip_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_clk_wiz_0_0 || ORIG_REF_NAME==v7_bd_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_clk_wiz_0_0 || ORIG_REF_NAME==v7_bd_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_clk_wiz_0_0 || ORIG_REF_NAME==v7_bd_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/v7_bd/ip/v7_bd_clk_wiz_0_0/v7_bd_clk_wiz_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==v7_bd_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==v7_bd_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/v7_bd/ip/v7_bd_proc_sys_reset_0_0/v7_bd_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_xadc_wiz_0_0/v7_bd_xadc_wiz_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_xadc_wiz_0_0/v7_bd_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v7_bd_xadc_wiz_0_0 || ORIG_REF_NAME==v7_bd_xadc_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/v7_bd/ip/v7_bd_xbar_0/v7_bd_xbar_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_input_ram_0_0/v7_bd_axi_bram_ctrl_input_ram_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_input_ram_4_0/v7_bd_axi_bram_ctrl_input_ram_4_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_output_ram_0_0/v7_bd_axi_bram_ctrl_output_ram_0_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_axi_bram_ctrl_input_ram_1_0/v7_bd_axi_bram_ctrl_input_ram_1_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_s00_regslice_0/v7_bd_s00_regslice_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_s00_data_fifo_0/v7_bd_s00_data_fifo_0_ooc.xdc

# XDC: bd/v7_bd/ip/v7_bd_m02_regslice_0/v7_bd_m02_regslice_0_ooc.xdc

# XDC: bd/v7_bd/v7_bd_ooc.xdc
