# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /data/skamat/Github/VivadoHLS/Make_LUT_MET/Bhawna/Vivado/ctp7_hls_demo/ctp7_hls_demo.srcs/sources_1/ip/pattern_bram/pattern_bram.xci
# IP: The module: 'pattern_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/skamat/Github/VivadoHLS/Make_LUT_MET/Bhawna/Vivado/ctp7_hls_demo/ctp7_hls_demo.srcs/sources_1/ip/pattern_bram/pattern_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pattern_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /data/skamat/Github/VivadoHLS/Make_LUT_MET/Bhawna/Vivado/ctp7_hls_demo/ctp7_hls_demo.srcs/sources_1/ip/pattern_bram/pattern_bram.xci
# IP: The module: 'pattern_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/skamat/Github/VivadoHLS/Make_LUT_MET/Bhawna/Vivado/ctp7_hls_demo/ctp7_hls_demo.srcs/sources_1/ip/pattern_bram/pattern_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pattern_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
