# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /data/skamat/Github/VivadoHLS/Make_LUT_MET/Bhawna/Vivado/ctp7_hls_demo/ctp7_hls_demo.srcs/sources_1/ip/Make_LUT_MET_0/Make_LUT_MET_0.xci
# IP: The module: 'Make_LUT_MET_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/skamat/Github/VivadoHLS/Make_LUT_MET/Bhawna/Vivado/ctp7_hls_demo/ctp7_hls_demo.srcs/sources_1/ip/Make_LUT_MET_0/constraints/Make_LUT_MET_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Make_LUT_MET_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /data/skamat/Github/VivadoHLS/Make_LUT_MET/Bhawna/Vivado/ctp7_hls_demo/ctp7_hls_demo.srcs/sources_1/ip/Make_LUT_MET_0/Make_LUT_MET_0.xci
# IP: The module: 'Make_LUT_MET_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/skamat/Github/VivadoHLS/Make_LUT_MET/Bhawna/Vivado/ctp7_hls_demo/ctp7_hls_demo.srcs/sources_1/ip/Make_LUT_MET_0/constraints/Make_LUT_MET_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Make_LUT_MET_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
